### PR TITLE
Update data.py

### PR DESCRIPTION
**Pull request by apin28**
thanks

### CODE REVIEW

**Comment by Aethese** [comment]
why do people do this

**Comment by AstroOrbis** [comment]
its not even a valid token lmao

**Comment by Aethese** [comment]
> its not even a valid token lmao

that's because discord has web crawlers to detect people like this guy so they can make the token invalid

**Comment by AstroOrbis** [comment]
It only works if you post the link somewhere in discord right? Happened to me once.

**Comment by Aethese** [comment]
like i said they have web crawlers. they crawl the web finding idiots like this who post their token online so they can make said token invalid.

**Comment by ARealWant** [comment]
> It only works if you post the link somewhere in discord right? Happened to me once.

Happens everywhere at GitHub, they're bots at Discord which are able to recoginize tokens, they put them in GH Gist so Discord unvalidate the token for the user, send them a Direct Message about what happened and how they's able to create a new token. So as Aethese said they're Webcrawlers scanning GitHub for Discord tokens, the user that put their token into this PQ has an invalid token now.

**Pull request closed without merging**
